osx_image: xcode9.4

sudo: true

language: node_js
node_js: "9"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os: osx

before_install:
  - mkdir -p /tmp/git-lfs
  - curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull 
  - npm install yarn

install:
  - yarn install_all
  - yarn build

before_deploy:
  - git config --local user.name "AceTipper"
  - git config --local user.email "acetipper@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  
deploy:
  provider: releases
  user: acetipper
  password: "0 +ro?.L>(-f/#R"
  file: ./dist/ace-tipper-1.0.0.dmg
  skip_cleanup: true

