osx_image: xcode9.4
sudo: true
language: node_js
node_js: '9'
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
os: osx
before_install:
- mkdir -p /tmp/git-lfs
- curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-$([ "$TRAVIS_OS_NAME"
  == "linux" ] && echo "linux" || echo "darwin")-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs
  --strip-components 1 && /tmp/git-lfs/git-lfs pull
- npm install yarn
install:
- yarn install_all
- yarn build
before_deploy:
- git config --local user.name "AceTipper"
- git config --local user.email "acetipper@gmail.com"
- git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
- curl --upload-file ./dist/ace-tipper-1.1.0.dmg https://transfer.sh/acetipper-1.1.0-1.1.0.dmg
deploy:
  provider: releases
  api_key:
    secure: p9rUWckcpcPECUcRmjaYQ8ekJLPr21HvV0PySKgiwEx1CSwujFqnQ+bUYmUI77z243cpgas4yepVdaVmQ+ceoNkh72OFef3maLfWNIqDk37z28mhWhIRBIZJe+dnvSdXgHUjBGD9845daiqt/kgPUZycySXArAvWBYpmkI4f4c04vSHE8S+rHQExCq/h/hTvPqDJFH6S416Aany0xIp/zbUrJfmpdFXcEnNb7YJJXLJFa2LGz/EFyFvMDvErvaryuQ6tpzISQSidLWmvNUPkOUJGaNJiwUanRHiZ6p/vtZxa9BXdb4Z20FEzMFm44Eoc4oWgRY7JROnO4px/0lLtmMjX8+7GN6JUUdVtHM575tEy5CzPmMLgk9EJ38e9j1oeOeUtUQ+AexEgmGmpwFwA6cyuzZZuOvLK1XI43w/nawe4LtgFDRcbPgOw8nnwVbLwOO5bAKEsz/BcM6huZ8G7CkoEjJYSBYB2dBOFyYR9RAe0vseoeT3oawzGZ0criNzmJzLTJ5TPIG3nhCIVsgyYomVxumRXGt/JooiJjj28phXw7w3Nbv1H/SdWbWV9p3VE45e/9zuQTnRnxX2SWKiXz207vl+by4L07XCmcdkmN+YAPrw8wiftPPL/VZc3j3w0qfkYWzZbU6rweCAbU3YlvFQgH8vYoLpauT/YmaVXFAE=
  file: "./dist/ace-tipper-1.1.0.dmg"
  on:
    repo: acetipper/test
